services:
  backend:
    image: ghcr.io/loudbooks/pastebook-backend:latest
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/pastebook
      - SPRING_DATA_MONGODB_DATABASE=pastebook
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=pastebook
    depends_on:
      - mongo
    networks:
      - pastebook-network

  frontend:
    image: ghcr.io/loudbooks/pastebook-frontend:latest
    ports:
      - '3000:3000'
    environment:
      - TITLE=Teak's Tweaks Paste
      - DESCRIPTION=Teak's Tweaks Paste is an aesthetic, effortless way to share your blocks of text, and respects your privacy by automatically deleting your pastes.
    depends_on:
      - backend
    networks:
      - pastebook-network
    pull_policy: always

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: pastebook
    volumes:
      - mongo-data:/data/db
    networks:
      - pastebook-network
    pull_policy: always

volumes:
  mongo-data:

networks:
  pastebook-network:
    driver: bridge
