services:
  backend:
    image: ghcr.io/loudbooks/pastebook-backend:latest
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/pastebook
      - SPRING_DATA_MONGODB_DATABASE=pastebook
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=pastebook
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      - mongo
      - minio
    networks:
      - pastebook-network

  frontend:
    image: ghcr.io/loudbooks/pastebook-frontend:latest
    ports:
      - '8000:8000'
    environment:
      - TITLE=Teak's Tweaks Paste
      - DESCRIPTION=Teak's Tweaks Paste
      - DISABLE_NEW=FALSE
    depends_on:
      - backend
    networks:
      - pastebook-network
    pull_policy: always

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: pastebook
    volumes:
      - mongo-data:/data/db
    networks:
      - pastebook-network
    pull_policy: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data/db
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data/db
    ports:
      - '9000:9000'
    networks:
      pastebook-network:
        aliases:
          - pastebook.minio
    pull_policy: always

volumes:
  mongo-data:
  minio-data:

networks:
  pastebook-network:
    driver: bridge
